POST http://localhost:3000/api/whatsapp/sendmessage
Content-Type: application/json

{
    "number":["", ""],
    "message":"Happy New Year 2025",
    "imageUrl": "https://khadsecollege.in/wp-content/uploads/2024/12/Happy-New-Year-2025-Wishes-1448x2048.webp",
    "scheduleTime": "48 14 * * *"
}

###
GET http://localhost:3000/api/whatsapp/generateqrcode
