POST http://localhost:3000/api/whatsapp/sendmessage
Content-Type: application/json

{
    "number":["8500191936", "9573131446"],
    "message":"Hi",
    "scheduleTime": "17 23 * * *"
}

###
GET http://localhost:3000/api/whatsapp/generateqrcode